apiVersion: v1
kind: Service
metadata:
  name: edgex-core-metadata
  labels:
    app.kubernetes.io/app: edgex-core-metadata
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.2.0
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.2.0

spec:
  selector:
    app.kubernetes.io/app: edgex-core-metadata
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.2.0
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.2.0

  ports:
  - port: 48081
    name: "port-48081"