apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.edgex.core.command.name }}
  labels:
    {{- include "edgex.labels" (dict "ctx" . "AppName" $.Values.edgex.core.command.name) | indent 4 }}
spec:
  selector:
    {{- include "edgex.labels" (dict "ctx" . "AppName" $.Values.edgex.core.command.name) | indent 4 }}
  ports:
  - port: {{ .Values.edgex.core.command.port }}
    name: "port-{{ .Values.edgex.core.command.port}}"