apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.edgex.redis.name }}
  labels:
    {{- include "edgex.labels" (dict "ctx" . "AppName" $.Values.edgex.redis.name) | indent 4 }}

spec:
  storageClassName: {{ .Values.edgex.redis.storageClassName }}
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/redis-volume"
