apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.edgex.core.data.name }}
  labels:
    {{- include "edgex.labels" (dict "ctx" . "AppName" $.Values.edgex.core.data.name) | indent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "edgex.labels" (dict "ctx" . "AppName" $.Values.edgex.core.data.name) | indent 4 }}
  ports:
  - port: {{ .Values.edgex.core.data.port }}
    name: "port-{{ .Values.edgex.core.data.port}}"
    nodePort: 30800