apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-redis
  labels:
    app.kubernetes.io/app: edgex-redis
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.2.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.2.1

spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/redis-volume"
